import { supabase } from '@/lib/supabase';
import type { RealtimeChannel, RealtimePostgresChangesPayload } from '@supabase/supabase-js';
import type { Conversation, ConversationStatus, Message, RemetenteTipo } from '@/types/chat';

export type { Conversation, Message };

const CONVERSAS_TABLE = 'fala_librelon_chat_conversas';
const MENSAGENS_TABLE = 'fala_librelon_chat_mensagens';
const ANEXOS_BUCKET = 'fala-librelon-chat-anexos';
const SIGNED_URL_TTL = 3600;

// ---- Conversas -----------------------------------------------------------------

export async function createConversa(data: {
  nome_solicitante: string;
  telefone_contato: string;
  email?: string | null;
  assunto?: string | null;
}): Promise<Conversation> {
  // Same fair round-robin RPC atuapolitica-frontend's ticket/chat creation uses,
  // so a citizen always has a dedicated atendente from the first message,
  // regardless of which front-end they used.
  const { data: assignedAtendente, error: rpcError } = await supabase.rpc(
    'fala_librelon_next_atendente',
  );
  if (rpcError) throw new Error(rpcError.message);

  const { data: result, error } = await supabase
    .from(CONVERSAS_TABLE)
    .insert([
      {
        nome_solicitante: data.nome_solicitante,
        telefone_contato: data.telefone_contato,
        email: data.email ?? null,
        assunto: data.assunto ?? null,
        assigned_atendente: assignedAtendente ?? null,
      },
    ])
    .select()
    .single();

  if (error) throw new Error(error.message);
  return result as Conversation;
}

export async function getConversa(id: string): Promise<Conversation | null> {
  const { data, error } = await supabase
    .from(CONVERSAS_TABLE)
    .select('*')
    .eq('id', id)
    .maybeSingle();
  if (error) throw new Error(error.message);
  return data as Conversation | null;
}

export async function findConversasByPhone(telefone: string): Promise<Conversation[]> {
  const { data, error } = await supabase
    .from(CONVERSAS_TABLE)
    .select('*')
    .eq('telefone_contato', telefone)
    .order('last_message_at', { ascending: false, nullsFirst: false });
  if (error) throw new Error(error.message);
  return (data as Conversation[]) || [];
}

export async function updateConversaStatus(
  id: string,
  status: ConversationStatus,
): Promise<void> {
  const { error } = await supabase
    .from(CONVERSAS_TABLE)
    .update({ status, updated_at: new Date().toISOString() })
    .eq('id', id);
  if (error) throw new Error(error.message);
}

// ---- Mensagens -----------------------------------------------------------------

export async function listMensagens(conversaId: string): Promise<Message[]> {
  const { data, error } = await supabase
    .from(MENSAGENS_TABLE)
    .select('*')
    .eq('conversa_id', conversaId)
    .order('created_at', { ascending: true });
  if (error) throw new Error(error.message);

  const rows = (data as Message[]) || [];
  await Promise.all(rows.map(resolveAnexoUrl));
  return rows;
}

// Messages across several conversations at once — used by the widget's
// "Histórico" view (all of a returning citizen's past conversations).
export async function listMensagensFromConversas(conversaIds: string[]): Promise<Message[]> {
  if (conversaIds.length === 0) return [];
  const { data, error } = await supabase
    .from(MENSAGENS_TABLE)
    .select('*')
    .in('conversa_id', conversaIds)
    .order('created_at', { ascending: true });
  if (error) throw new Error(error.message);

  const rows = (data as Message[]) || [];
  await Promise.all(rows.map(resolveAnexoUrl));
  return rows;
}

// Fresh short-lived signed URL for a message's attachment, if any. Needed
// anywhere a message is added to local state OUTSIDE of listMensagens' own
// fetch — a just-sent message and a just-received realtime message both carry
// anexo_path but no anexo_url, since the signed URL is only ever generated by
// this call, never stored.
export async function resolveAnexoUrl(msg: Message): Promise<Message> {
  if (!msg.anexo_path) return msg;
  const { data: signed } = await supabase.storage
    .from(ANEXOS_BUCKET)
    .createSignedUrl(msg.anexo_path, SIGNED_URL_TTL);
  msg.anexo_url = signed?.signedUrl ?? null;
  return msg;
}

export async function sendMensagem(
  conversaId: string,
  data: {
    remetente_tipo: RemetenteTipo;
    remetente_nome: string;
    mensagem?: string | null;
    anexo?: { path: string; nome: string; mime: string | null; tamanho: number | null } | null;
  },
): Promise<Message> {
  const { data: msg, error } = await supabase
    .from(MENSAGENS_TABLE)
    .insert([
      {
        conversa_id: conversaId,
        remetente_tipo: data.remetente_tipo,
        remetente_nome: data.remetente_nome,
        mensagem: data.mensagem ?? null,
        anexo_path: data.anexo?.path ?? null,
        anexo_nome: data.anexo?.nome ?? null,
        anexo_mime: data.anexo?.mime ?? null,
        anexo_tamanho: data.anexo?.tamanho ?? null,
      },
    ])
    .select()
    .single();
  if (error) throw new Error(error.message);

  const now = new Date().toISOString();
  const { error: updError } = await supabase
    .from(CONVERSAS_TABLE)
    .update({ last_message_at: now, updated_at: now })
    .eq('id', conversaId);
  if (updError) console.warn('Failed to update conversa:', updError.message);

  return resolveAnexoUrl(msg as Message);
}

export async function markMensagensLidas(
  conversaId: string,
  viewerRemetenteTipo: RemetenteTipo,
): Promise<void> {
  const { error } = await supabase
    .from(MENSAGENS_TABLE)
    .update({ lido: true })
    .eq('conversa_id', conversaId)
    .neq('remetente_tipo', viewerRemetenteTipo)
    .eq('lido', false);
  if (error) console.warn('Failed to mark mensagens lidas:', error.message);
}

// ---- Attachments -----------------------------------------------------------------

// Same pattern as atuapolitica-frontend's uploadChatAnexo: private bucket, path
// prefixed by the owning conversation id. Browser File object directly (no RN
// document-picker uri indirection needed here).
export async function uploadChatAnexo(
  conversaId: string,
  file: File,
): Promise<{ path: string; nome: string; mime: string | null; tamanho: number | null }> {
  const safeName = file.name.replace(/[^\w.-]+/g, '_');
  const path = `${conversaId}/${Date.now()}_${safeName}`;

  const { error: upErr } = await supabase.storage
    .from(ANEXOS_BUCKET)
    .upload(path, file, { contentType: file.type || 'application/octet-stream', upsert: false });
  if (upErr) throw new Error(upErr.message);

  return {
    path,
    nome: file.name,
    mime: file.type || null,
    tamanho: file.size || null,
  };
}

// ---- Realtime -----------------------------------------------------------------

export function subscribeConversaMensagens(
  conversaId: string,
  onInsert: (payload: RealtimePostgresChangesPayload<Message>) => void,
): RealtimeChannel {
  return supabase
    .channel(`fl-chat-mensagens-${conversaId}`)
    .on(
      'postgres_changes',
      {
        event: 'INSERT',
        schema: 'public',
        table: MENSAGENS_TABLE,
        filter: `conversa_id=eq.${conversaId}`,
      },
      onInsert,
    )
    .subscribe();
}
